const ES_PHRASE_MAP = [
  ['World\'s Greatest Stretch', 'Estiramiento Global'],
  ['Band Shoulder Dislocates', 'Dislocaciones de Hombro con Banda'],
  ['Cat-Cow Flow', 'Flujo Gato-Vaca'],
  ['Downward Dog', 'Perro Boca Abajo'],
  ['Couch Stretch', 'Estiramiento Couch'],
  ['Pigeon Pose', 'Postura de la Paloma'],
  ['Shadow Boxing', 'Boxeo de Sombra'],
  ['Freestyle Bag Work', 'Trabajo Libre en Costal'],
  ['Heavy Bag', 'Costal Pesado'],
  ['Kettlebell', 'Pesa Rusa'],
  ['Dumbbell', 'Mancuerna'],
  ['Barbell', 'Barra'],
  ['Push-Ups', 'Flexiones'],
  ['Pull-Ups', 'Dominadas'],
  ['Chin-Ups', 'Dominadas Supinas'],
  ['Dead Hang', 'Colgado Pasivo'],
  ['Bent-Over Row', 'Remo Inclinado'],
  ['Pullover', 'Pullover'],
  ['Hammer Curls', 'Curl Martillo'],
  ['Bicep Curls', 'Curl de Bíceps'],
  ['Skullcrushers', 'Extensiones de Tríceps'],
  ['Lateral Raises', 'Elevaciones Laterales'],
  ['Front Raises', 'Elevaciones Frontales'],
  ['Overhead Press', 'Press Militar'],
  ['Floor Press', 'Press en Suelo'],
  ['Romanian Deadlift', 'Peso Muerto Rumano'],
  ['Deadlift', 'Peso Muerto'],
  ['Goblet Squat', 'Sentadilla Goblet'],
  ['Bodyweight Squats', 'Sentadillas con Peso Corporal'],
  ['Jump Squats', 'Sentadillas con Salto'],
  ['Squat Jumps', 'Saltos de Sentadilla'],
  ['Lunges', 'Zancadas'],
  ['Split Squat', 'Sentadilla Búlgara'],
  ['Single-Leg', 'Una Pierna'],
  ['Calf Raises', 'Elevaciones de Pantorrilla'],
  ['Wall Sit', 'Sentadilla Isométrica en Pared'],
  ['Plank', 'Plancha'],
  ['Side Plank', 'Plancha Lateral'],
  ['Russian Twists', 'Giros Rusos'],
  ['Bicycle Crunches', 'Abdominales Bicicleta'],
  ['Leg Raises', 'Elevaciones de Piernas'],
  ['Knee Raises', 'Elevaciones de Rodillas'],
  ['Mountain Climbers', 'Escaladores'],
  ['Burpees', 'Burpees'],
  ['Thrusters', 'Thrusters'],
  ['Turkish Get-Up', 'Levantada Turca'],
  ['Windmill', 'Molino'],
  ['Ab Wheel Rollouts', 'Rollouts con Rueda Abdominal'],
  ['Ab Wheel Kneeling Rollout', 'Rollout Arrodillado con Rueda Abdominal'],
  ['Band Pull-Apart', 'Aperturas con Banda'],
  ['Band Face Pulls', 'Face Pull con Banda'],
  ['Band Rows', 'Remo con Banda'],
  ['Band Squats', 'Sentadillas con Banda'],
  ['Band Lateral Walks', 'Caminata Lateral con Banda'],
  ['Band Push-Ups', 'Flexiones con Banda'],
  ['Band Overhead Press', 'Press Militar con Banda'],
  ['Inverted Rows', 'Remo Invertido'],
  ['Bodyweight Rows', 'Remo con Peso Corporal'],
  ['Superman Hold', 'Superman Isométrico'],
  ['Close-Grip', 'Agarre Cerrado'],
  ['Wide-Grip', 'Agarre Amplio'],
  ['Strict', 'Estricto'],
  ['Standard', 'Estándar'],
  ['Diamond', 'Diamante'],
  ['Wide', 'Amplio'],
  ['Pike', 'Pica'],
  ['Decline', 'Declinadas'],
  ['Deep', 'Profundas'],
  ['on Handles', 'en Soportes'],
  ['(Floor)', '(Suelo)'],
  ['(Standing)', '(De Pie)'],
  ['(Bar Low)', '(Barra Baja)'],
  ['(Table/Bar)', '(Mesa/Barra)'],
  ['Imaginary', 'Imaginario'],
  ['HIIT', 'HIIT'],
  ['Clean & Press', 'Cargada y Press'],
  ['Push Press', 'Push Press'],
  ['Row', 'Remo'],
  ['Press', 'Press'],
];

function autoTranslateExerciseName(name) {
  let translated = name;
  ES_PHRASE_MAP.forEach(([en, es]) => {
    translated = translated.replace(new RegExp(en, 'g'), es);
  });
  return translated;
}

export function getExerciseDisplayName(exercise, lang = 'en') {
  if (!exercise) return '';
  if (lang !== 'es') return exercise.name;
  if (exercise.nameEs) return exercise.nameEs;
  return autoTranslateExerciseName(exercise.name);
}
